import os

# Basic configuration
API_NAME = os.getenv('API_NAME')
API_VERSION = os.getenv('API_VERSION')
JWT_SECRET = os.getenv('JWT_SECRET') # The JWT secret string
PRODUCTION_SERVER_URL = os.getenv('PRODUCTION_SERVER_URL')
DEVELOPMENT_SERVER_URL = os.getenv('DEVELOPMENT_SERVER_URL')
LOCALHOST_SERVER_URL = os.getenv('LOCALHOST_SERVER_URL')

# Database configuration
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PORT = os.getenv('DATABASE_PORT')
DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_URL = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"

# Default user configuration
DEFAULT_USER_PASSWORD = os.getenv('DEFAULT_USER_PASSWORD')
DEFAULT_USER_NAME = os.getenv('DEFAULT_USER_NAME')
