version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    container_name: methods_solver_backend_database
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mysql_methods_solver_backend_network_data:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - methods_solver_backend_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  methods_solver_backend_api:
    image: ghcr.io/juanfeliperestrepobuitrago/numericalanalysisfinalproject/methods_solver_backend_api:latest
    container_name: methods_solver_backend_api
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - API_NAME=backend_numerical_methods
      - API_VERSION=v1.2.1
      - JWT_SECRET=supersecretkeythatissufficientlylong123
      - PRODUCTION_SERVER_URL=http://method-solver.sytes.net
      - DEVELOPMENT_SERVER_URL=http://method-solver.sytes.net
      - LOCALHOST_SERVER_URL=http://localhost:8000
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=numerical_methods_api
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DEFAULT_USER_NAME=eafit
      - DEFAULT_USER_PASSWORD=Analisis123
    networks:
      - methods_solver_backend_network
    restart: always

  nginx:
    image: nginx:alpine3.19
    container_name: methods_solver_backend_nginx
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf  # Mount a custom nginx.conf file
    depends_on:
      - methods_solver_backend_api 
    networks:
      - methods_solver_backend_network
    restart: always

volumes:
  mysql_methods_solver_backend_network_data: 

networks:
  methods_solver_backend_network:
    driver: bridge
