version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    container_name: methods_solver_backend_database
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mysql_methods_solver_backend_network_data:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - methods_solver_backend_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  methods_solver_backend_api:
    image: piper04/methods_solver_backend_api:latest
    container_name: methods_solver_backend_api
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=jpr_reformas_construcciones_sas
      - DB_PORT=3306
    networks:
      - methods_solver_backend_network
    restart: always

  nginx:
    image: nginx:alpine3.19
    container_name: methods_solver_backend_nginx
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf  # Mount a custom nginx.conf file
    depends_on:
      - methods_solver_backend_api 
    networks:
      - methods_solver_backend_network
    restart: always

volumes:
  mysql_methods_solver_backend_network_data: 

networks:
  methods_solver_backend_network:
    driver: bridge
